# Generated by Django 3.1.3 on 2020-11-03 10:00
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Isbn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn13", models.CharField(default=None, max_length=13, null=True)),
                ("isbn10", models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("publication_date", models.DateField()),
                ("page_count", models.IntegerField()),
                ("lang", models.CharField(max_length=2)),
                ("thumbnail", models.URLField()),
                ("author", models.ManyToManyField(to="books.Author")),
                (
                    "isbn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="books.isbn"
                    ),
                ),
            ],
        ),
    ]
