# Generated by Django 3.1.3 on 2020-11-05 16:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="page_count",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
