# Generated by Django 3.1.3 on 2020-11-03 17:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=254),
        ),
    ]
