# Generated by Django 3.1.3 on 2020-11-05 16:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_auto_20201105_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.CharField(max_length=10),
        ),
    ]
